apiVersion: v1
kind: PersistentVolume
metadata:
  name: weblog-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/weblog"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblog-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluentd.conf: |
    <source>
      @type tail
      format none
      path /var/log/access.log
      tag count.format1
    </source>

    <match *.**>
    @type stdout
    id stdout_output
    </match>
---
apiVersion: v1
kind: Pod
metadata:
  name: weblog-pv-pod
spec:
  volumes:
    - name: weblog-pv-storage
      persistentVolumeClaim:
        claimName: weblog-pv-claim
    - name: log-config
      configMap:
        name: fluentd-config
  containers:
    - name: webcont
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/log/nginx"
          name: weblog-pv-storage
        - name: log-config
          mountPath: "/etc/fluentd-config"
    - name: fdlogger
      image: fluent/fluentd
      volumeMounts:
        - name: weblog-pv-storage
          mountPath: "/var/log"
        - name: log-config
          mountPath: "/etc/fluentd-config"
      env:
        - name: FLUENTD_OPT
          value: -c /etc/fluentd-config/fluentd.conf
