apiVersion: v1
data:
  TEST_KEY: foobarbaz
  test.key: foobarbaz
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: lab-5-configmap
---
apiVersion: v1
data:
  secret.key: dWx0cmEgc2VjcmV0IHNlY3JldA==
kind: Secret
metadata:
  creationTimestamp: null
  name: lab-5-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-demo-app
  name: k8s-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-demo-app
    spec:
      containers:
      - image: api
        name: k8s-demo-app
        resources: {}
        imagePullPolicy: IfNotPresent
        env:
        - name: test.key
          valueFrom:
            configMapKeyRef:
              name: lab-5-configmap
              key: test.key
        - name: secret.key
          valueFrom:
            secretKeyRef:
              name: lab-5-secret
              key: secret.key
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-demo-app
  name: k8s-demo-app
spec:
  ports:
    - name: 80-8080
      port: 81
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-demo-app
  type: ClusterIP
status:
  loadBalancer: {}
